Traceback (most recent call last):
  File "/Users/naftali/opt/anaconda3/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/naftali/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/naftali/opt/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/naftali/opt/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/naftali/opt/anaconda3/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/Users/naftali/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 560, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/naftali/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/naftali/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
!pip install gurobipy

# Import gurobi library
from gurobipy import * # This command imports the Gurobi functions and classes.

import numpy as np

# create new model
m = Model('Beaver Creek Pottery Company ')
x1 = m.addVar(lb = 0, vtype = GRB.CONTINUOUS, name='x1') 
x2 = m.addVar(lb = 0, vtype = GRB.CONTINUOUS, name='x2')

m.setObjective((4-0.1*x1)*x1+(5-0.2*x2)*x2, GRB.MAXIMIZE)
m.addConstr(1*x1+2*x2==40, 'const1')

m.optimize()

#display optimal production plan
for v in m.getVars():
  print(v.varName, v.x)
print('optimal total revenue:', m.objVal)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mGurobiError[0m                               Traceback (most recent call last)
[0;32m<ipython-input-1-d235cf0d5ec0>[0m in [0;36m<module>[0;34m[0m
[1;32m      7[0m [0;34m[0m[0m
[1;32m      8[0m [0;31m# create new model[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 9[0;31m [0mm[0m [0;34m=[0m [0mModel[0m[0;34m([0m[0;34m'Beaver Creek Pottery Company '[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     10[0m [0mx1[0m [0;34m=[0m [0mm[0m[0;34m.[0m[0maddVar[0m[0;34m([0m[0mlb[0m [0;34m=[0m [0;36m0[0m[0;34m,[0m [0mvtype[0m [0;34m=[0m [0mGRB[0m[0;34m.[0m[0mCONTINUOUS[0m[0;34m,[0m [0mname[0m[0;34m=[0m[0;34m'x1'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     11[0m [0mx2[0m [0;34m=[0m [0mm[0m[0;34m.[0m[0maddVar[0m[0;34m([0m[0mlb[0m [0;34m=[0m [0;36m0[0m[0;34m,[0m [0mvtype[0m [0;34m=[0m [0mGRB[0m[0;34m.[0m[0mCONTINUOUS[0m[0;34m,[0m [0mname[0m[0;34m=[0m[0;34m'x2'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32msrc/gurobipy/env.pxi[0m in [0;36mgurobipy.Env.__init__[0;34m()[0m

[0;32msrc/gurobipy/gurobi.pxi[0m in [0;36mgurobipy.gurobi._getdefaultenv[0;34m()[0m

[0;32msrc/gurobipy/env.pxi[0m in [0;36mgurobipy.Env.__init__[0;34m()[0m

[0;31mGurobiError[0m: No Gurobi license found (user naftali, host Naftalis-MacBook-Pro-15.local, hostid d3c3e9a1, cores 6)
GurobiError: No Gurobi license found (user naftali, host Naftalis-MacBook-Pro-15.local, hostid d3c3e9a1, cores 6)

